# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-27 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0004_auto_20190219_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='requester',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
