# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-31 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0002_auto_20190115_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Reserved', 'Reserved'), ('Available', 'Available')], default='Available', max_length=100),
            preserve_default=False,
        ),
    ]
