# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-31 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0003_room_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('hours', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='reservationrequest',
            name='room',
        ),
        migrations.RemoveField(
            model_name='room',
            name='status',
        ),
        migrations.DeleteModel(
            name='ReservationRequest',
        ),
        migrations.AddField(
            model_name='room',
            name='reservations',
            field=models.ManyToManyField(to='Rooms.Reservation'),
        ),
    ]
