# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-03 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0005_auto_20190403_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='repeat_weeks',
            field=models.IntegerField(default=1),
        ),
    ]
