# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-09 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0006_reservation_repeat_weeks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='repeat_weeks',
            field=models.IntegerField(default=0),
        ),
    ]
