# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-10 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0007_auto_20190409_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='crn',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='reservations',
            field=models.ManyToManyField(blank=True, to='Rooms.Reservation'),
        ),
    ]
