# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-29 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20190129_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='major',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
