# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-29 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_auto_20190129_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[(b'Student', b'Student'), (b'Student Worker', b'Student Worker'), (b'Teacher', b'Teacher'), (b'Staff', b'Staff')], default='Student', max_length=20),
        ),
    ]
