# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-21 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_auto_20190226_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Users.UserType'),
        ),
    ]
